In [5]:
import numpy as np
import scipy as sp
import pandas as pd

from sklearn.preprocessing import Imputer

#read the csv into a dataframe
df = pd.read_csv('qa.csv')

In [2]:
df

0             1      2
0  id  years_in_pos  bonus
1   1             4    300
2   2           NaN    200
3   3             6    500
4   4             3    NaN
5   5             3    NaN
6   6             2    100

In [5]:
df.count()

id              6
years_in_pos    5
bonus           4
dtype: int64

In [6]:
df.describe()

id  years_in_pos       bonus
count  6.000000      5.000000    4.000000
mean   3.500000      3.600000  275.000000
std    1.870829      1.516575  170.782513
min    1.000000      2.000000  100.000000
25%    2.250000      3.000000  175.000000
50%    3.500000      3.000000  250.000000
75%    4.750000      4.000000  350.000000
max    6.000000      6.000000  500.000000

In [7]:
imp = Imputer(missing_values='NaN', strategy='median', axis=0)
imputed_DF = pd.DataFrame(imp.fit_transform(df))
imputed_DF.columns = df.columns
imputed_DF.index = df.index

In [8]:
imputed_DF.describe()

id  years_in_pos       bonus
count  6.000000      6.000000    6.000000
mean   3.500000      3.500000  266.666667
std    1.870829      1.378405  132.916014
min    1.000000      2.000000  100.000000
25%    2.250000      3.000000  212.500000
50%    3.500000      3.000000  250.000000
75%    4.750000      3.750000  287.500000
max    6.000000      6.000000  500.000000

In [9]:
imputed_DF

id  years_in_pos  bonus
0  1.0           4.0  300.0
1  2.0           3.0  200.0
2  3.0           6.0  500.0
3  4.0           3.0  250.0
4  5.0           3.0  250.0
5  6.0           2.0  100.0

In [10]:
 from sklearn.preprocessing import MinMaxScaler

In [11]:
scaler = MinMaxScaler()

In [12]:
print(scaler.fit(imputed_DF))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [13]:
print(scaler.data_max_)

[   6.    6.  500.]


In [14]:
print(scaler.transform(imputed_DF))

[[ 0.     0.5    0.5  ]
 [ 0.2    0.25   0.25 ]
 [ 0.4    1.     1.   ]
 [ 0.6    0.25   0.375]
 [ 0.8    0.25   0.375]
 [ 1.     0.     0.   ]]
